### ISSUE TITLE
Line spacing differences

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#118]
**Bug Description**
Depending on how text is copied/pasted, Ctrl-v //ignores carriage returns when copied from web page or pdf/word document, unless 'sanitized' via a intermin copy/paste via text editor, then spacing may be correct-however pdf files can introduce unusual characters//, Ctrl-Shift-v //unequal line sizes between paragraphs// - or carriage return keystrokes, distance between lines changes.

**Steps to Reproduce**
1. Add a line of text, hit Shift-Enter
2. Add a line of text, hit Enter
3. Add a line of text, hit Enter
4. Add a line of text, hit Enter
5. Add a line of text, hit Shift-Enter
6. Add a line of text

**Expected behavior**
Line spacing should be equivalent?
Spacing appears more pronounced at smaller font sizes

**Screenshots** (optional)
![screen](https://user-images.githubusercontent.com/88691671/185015803-76e5f9ba-73a0-4d28-b1e8-7dea3e3eb087.png)
![screen01](https://user-images.githubusercontent.com/88691671/185015817-69934957-e8f7-4a94-913e-c900eb495748.png)
![screen02](https://user-images.githubusercontent.com/88691671/185015881-5e83fd14-0b3e-4425-b1c8-f7ed105d78e6.png)

**Device information**
 - Operating System: Raspberry PI/Debian Bullseye, latest updates

**Comments**
Way back in my old html/javascript coding days, there was a function called the 'no-break space' or something, whereby Shift-Enter was invoked to maintain spacing in web documents... is this what is occurring here?

Trying to avoid the text editor 'sanitizing' step as it strips font attributes (bold, color, etc) which I have to manually correct.

**Comment by Cuperino** [comment]
> Line spacing should be equivalent?

Yes.

I didn't make them equivalent because I thought the extra space would be good for adding a small pause or breather at the end of paragraphs. But I can see why that would be problematic given PDFs often deal with line endings incorrectly to maximize compression and, perhaps, compatibility.

Maybe if I could make it so you could control this property for all paragraphs with a slider... But that would be a new feature for a future minor update. I'll make spacing the same for the micro/bug fix release.

**Comment by videosmith** [comment]
For paragraphs, that could be useful as an option. Most of my client's just request a blank line, so the next paragraph reveals without a significant delay.

The situation I have is when a client asks for a line break at the end of a sentence so the next sentence starts on a new line- and it is not spaced the same (some client's can be petty/ocd-heavy lol).

PDFs are a headache to import/copy/paste in any word processor except a dedicated pdf editor imo.

**Comment by Cuperino** [comment]
> For paragraphs, that could be useful as an option. Most of my client's just request a blank line, so the next paragraph reveals without a significant delay.

Paragraph slider, done.

> The situation I have is when a client asks for a line break at the end of a sentence so the next sentence starts on a new line- and it is not spaced the same (some client's can be petty/ocd-heavy lol).

Technically that's what Shift+Enter is for, but most people aren't even aware that's a thing. Since it takes two key presses, it can be more convenient to just set paragraph height to 0 and only press enter. Paragraph height is now 0 by default.

> PDFs are a headache to import/copy/paste in any word processor except a dedicated pdf editor imo.

That's because most PDFs often break paragraphs into their individual lines. In the worse cases, only drawing calls are saved instead of text. Since PDFs and PostScript are not meant for humans to read, things get pretty ugly in there.
