### ISSUE TITLE
Is the default size correct?

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#119]
**Bug Description**
Default font size appears smaller than 'small fonts' size

**Steps to Reproduce**
1. Run program

**Expected behavior**
Larger default font size as in prior versions

**Screenshots** (optional)
![screen02](https://user-images.githubusercontent.com/88691671/185475691-e871c073-d573-44ef-9fe4-f88048f13d71.png)
![screen01](https://user-images.githubusercontent.com/88691671/185475706-cc2d2525-543a-4e66-b34e-db2533c05cbb.png)

**Device information**
 - Operating System: Debian Bullseye, latest updates

**Additional context**

**Comment by Cuperino** [comment]
Is this the first time you run QPrompt on this system? QPrompt remembers your settings from previous sessions, including those from earlier versions of the software. It's probable that "63% font size" is the setting you were using when you closed QPrompt at the end of your last session...

v1.1.1 now also saves line height, which wasn't saved on previous versions of the software, and it adds paragraph spacing, which didn't exist previously. There is a bug with paragraph spacing, where it doesn't get applied to its full extent on application startup. This only affects the demo script since it's loaded by default. The property is applied correctly in all other circumstances.

To restore QPrompt's settings to their defaults on Linux, delete `~/.config/Cuperino/qprompt.conf`.

**Comment by videosmith** [comment]
No. I usually leave it at the default 90% on this Dell laptop.

Interestingly, the install on a RPi 400 defaults to this:
![Screenshot from 2022-08-18 16-40-31](https://user-images.githubusercontent.com/88691671/185491383-22568a0a-1f8c-4d8d-8cb6-c749d23800aa.png)
![Screenshot from 2022-08-18 16-39-39](https://user-images.githubusercontent.com/88691671/185491421-afe2af1d-908a-4a19-812d-57aa2557fb8c.png)

I understand the bold typeface is the result of me using 'bold' as a system font attribute.

**Comment by Cuperino** [comment]
> No. I usually leave it at the default 90% on this Dell laptop.

Huh, that is interesting. Another possibility is you've may have set the alternate (smaller) font size slider to a large size and used them inversely in a previous session. The values for both slider configurations are saved. Nevertheless, QPrompt intentionally doesn't remember which of the two font values you where using when the program was closed. It always loads the value from the slider that allows for bigger font sizes to be used, because they don't share the same ranges.

> I understand the bold typeface is the result of me using 'bold' as a system font attribute.

That is correct. I tried overriding the value in QPrompt but it didn't take effect. I need to look deeper into this, but I won't be doing that soon because the effect so far is limited to systems that provide Plasma theme configurations, which the DE or distribution should have options for configuring.

**Comment by videosmith** [comment]
Deleting the .conf file appears to have restored the default font size. Thank you!

**Comment by Cuperino** [comment]
Because the .conf is a text file, you can manipulate it and QPrompt will attempt to load it's values. If the file or an entry is missing, QPrompt will create it upon launch.

Settings are stored using QML's Settings API. Quoting from Qt's documentation: "The information is stored in the system registry on Windows, and in XML preferences files on macOS. On other Unix systems, in the absence of a standard, INI text files are used." Therefore, how to delete and manipulate settings varies from one system to another, but in all cases the settings themselves should be self explanatory or match the naming schemes in QPrompt's UI.
