### ISSUE TITLE
Reverse scroll limitation using mouse wheel/velocity slider

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#125]
**Bug Description**
When using arrow keys to control scroll speed, both forward and reverse scroll directions are supported.
However when using the Velocity slider or 'Using scroll as velocity dial' with the mouse wheel, only forward scroll appears to be supported.

Is reverse scrolling using the slider or mouse wheel possible?

**Steps to Reproduce**
1. Disable throttling
2. Enable 'Use scroll as velocity dial'
3. Drag velocity slider while scrolling

**Expected behavior**
Slider and mouse wheel should have same behavior as Arrow keys

**Device information**
 - Operating System: Debian Bullseye x64, latest updates
 - using .AppImage release
![screen](https://user-images.githubusercontent.com/88691671/188325231-134faa4e-1210-4563-81ce-fe52a7037132.png)

**Comment by Cuperino** [comment]
Pressing the plus sign to the left of "Velocity", changes the slider's range to allow for a "negative velocity" (a.k.a. speed in the opposite direction). It also enables the mouse wheel to accelerate in reverse when "Use scroll as velocity dial" is enabled. By default, the velocity slider is set to use positive values only, because it would be jarring for talents if the prompter suddenly started moving in reverse when their expectation was for the operator to slow it down to a halt.

You can still use the arrow keys because the chance of accidentally going in reverse with the arrow keys is much lower than the chance of doing the same with a touch pad or mouse wheels that are not stepped. Click on the plus sign to the left of the mouse wheel to allow going in reverse. Using it like that is my personal preference, but it shouldn't become QPrompt's default because of the reason stated above.

**Comment by videosmith** [comment]
Perfect. Thank you.
