### ISSUE TITLE
Saving document automatically reloads previous save

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#126]
Hopefully this makes sense.
When saving the current script, saving button animates slower than usual, font color changes and prior deleted text reappears.
Rebooted/power cycled computer,  no change.
Was acting as if the deleted changes weren't fully updating in the .html file.
Reloading saved file displays correct saved version.

Only happened with one script, solution was to copy all text in current qprompt window then paste into a second qprompt window.

**Detailed description of display configuration** (if applicable)
Raspberry Pi 400 Bullseye, latest updates.

**Screenshots** (optional)
![20220908_132731](https://user-images.githubusercontent.com/88691671/189189448-25070d33-04ce-4036-b0fc-5d262a09a0da.jpg)

**Additional context**
i have a video of the issue but it won't upload here.
Attempted to email it to you (22.5mb)

**Comment by Cuperino** [comment]
The email was received by GitHub as a reply to a previous issue, but the attachment, unfortunately, was automatically removed. Please send the video to my e-mail javiercorderoperez@gmail.com, or upload to a file or video service such as Drive, MEGA, or YouTube.

**Comment by videosmith** [comment]
Resent

**Comment by Cuperino** [comment]
Thanks.

QPrompt's document re-loader is being triggered by QPrompt's own saves. This never proved to be an issue in any of my systems, but it is clear from the video that the file is being re-loaded before the system flushes the changes into the SD Card.

There are several ways this could be solved. I'll look into the options and include the fix in v1.1.2.

I did not think there would be a v1.1.2 this soon, but after having cracked the code for screen duplication, a point release is a must.

**Comment by videosmith** [comment]
Let me know if you need any more info.

**Comment by videosmith** [comment]
> [Cuperino](https://github.com/Cuperino) closed this as [completed](https://github.com/Cuperino/QPrompt/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/Cuperino/QPrompt/commit/6d48f264821e0cd5eb44f1e6c9b5b2b82d881855

Does this page mean the fix needs to be manually rebuilt into your distribution?

**Comment by Cuperino** [comment]
That page, and the link above it, show the git commits (changes to the code) pertaining to this issue. The links were automatically generated when I uploaded the commits to GitHub because I wrote this issue's ID on each of those commits' descriptions. The last link says "Cuperino closed this as completed in ____" because that commit description also indicates that its code fixes this issue. This automation saves time and helps developers keep track of code that solves specific issues.

Now it's just a matter of making a new build. I make them manually from various systems that run on two of my computers. The whole process takes me around 6-8 hours. This fix will be included in an update that I'm planning to release on Sunday, but you can always make a build yourself by following the steps at: [https://github.com/Cuperino/QPrompt/issues/38](https://github.com/Cuperino/QPrompt/issues/38). The deb package can be built in 2 hours, or in 30 minutes once you have everything setup. If you have questions on how to make a build for yourself, feel free to ask over at the forum.
