### ISSUE TITLE
Have mouse clicks passthrough to windows behind the promper's transparent background

### ISSUE THREAD

**Issue by haumacher** [Cuperino/QPrompt#138]
When prompting, I can make the background transparent so I can still see other apps on the desktop. However I can no longer  interact with those apps, because the mouse always hits the prompter in the foreground.

I'd like to produce videos where I'm presenting some application (using the application window as video background). To do this, I need to have still full control of the application I'm showing. The prompter text should scroll transparently over the application so I'm able to read the text while operating the application in the background.

**Comment by Cuperino** [comment]
Hello @haumacher,

Thank you for writing. This is a very challenging thing to achieve because it's the kind of feature that needs to be implemented once per operating system (supported OSs are Windows, macOS, Linux (X11 and Wayland), and Android); and it would conflict with security restrictions that are present in some of those systems to prevent hackers from logging mouse presses and stealing your personal information.

I'm going to leave this issue open in case anyone wants to tackle it, but I'm not going to work on it because there are other issues with higher priority that would also take a while to develop, and I fear that implementing this could cause anti-virus software to flag QPrompt as malware.

If anyone's interested in working on this, feel welcome to do so. I'm open to merging the feature into QPrompt if we can make sure that it is secure. Ideally Linux, Windows, and macOS would be supported but not all systems have to be from the start.

**Comment by Cuperino** [comment]
Closing issues that I won't be working on. If someone else wants to tackle it, they can submit a PR and re-open.
