### ISSUE TITLE
Open/read  Remote file from url

### ISSUE THREAD

**Issue by IVEN2022** [Cuperino/QPrompt#143]
Ability to open /read remote file from URL  for example    https://mydomain.com/test.txt 
what is the possibilities please 

thank you for the best software

**Comment by Cuperino** [comment]
Thank you for your kind words.

I know this can be done. The auto-reload feature will not work as it is; a TCP or HTTP "check and pull mechanism" should be implemented on top of the existing routines. The improved re-loading mechanism would then be re-used to solve issue #141, since that issue requires a JSON parser and a UI to configure it in addition to this.

**Comment by Cuperino** [comment]
Hey @IVEN2022, hope you're still around. This feature has been added to QPrompt's `main` and `v1.2` branches. Tomorrow I plan to release two updates:
- `v1.1.5` a bug fix release for the general public based of the v1.1 branch,
- and the first early-access build for `v1.2.0`, which contains this feature, and is available to Patreons

This feature was chosen in part thanks to the Patreons who voted for it. To vote for features in our surveys, and gain access to early builds, visit QPrompt's Patreon page and support the project: https://www.patreon.com/qpromptapp

Here's a screenshot of what this feature looks like at the time of writing:
![image](https://user-images.githubusercontent.com/1840407/221378833-56abc889-7f13-4d3d-beb8-d50ea3f67d7a.png)

**Comment by Taz2000** [comment]
This is exactly what I need! Thank you!
