### ISSUE TITLE
Saving confirmation lingering on screen

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#151]
**Bug Description**
Not certain if this is related to a prior similar issue, however saving results in an extended confirmation message.

**Expected behavior**
Should display briefly.

**Detailed description of display configuration** (if applicable)
Debian 11, with QPrompt 1.1.1 os mirror and 1.1.3 as previously discussed to determine a separate freezing issue.

**Screenshots** 
[

![20230201_090418](https://user-images.githubusercontent.com/88691671/216066228-e8919386-34af-45bf-b7f6-e3253affd4de.jpg)
![20230201_084748](https://user-images.githubusercontent.com/88691671/216066992-f6fddd81-7976-499c-accf-93cae927dfa5.jpg)

**Comment by Cuperino** [comment]
Was the app in full screen mode when the notification appeared?

**Comment by videosmith** [comment]
Yes
    On Wednesday, February 1, 2023, 10:55:00 AM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Was the app in full screen mode when the notification appeared?

**Comment by Cuperino** [comment]
I see... The path to the file is a long string of text. Kirigami is programmed in such way that the notification stays up for longer the longer the text is, so users have enough time to read everything. Other means of knowing "data saved successfully" aren't visible while in fullscreen, which is why I left the notification in place for this particular circumstance.

If I shorten or fix the notification's duration, it may not be enough time for slower readers to read. I don't know how Kirigami computes the time, but when I video edit, I usually follow this rule: "Any text that comes and goes should be relatively still for a period of at least 3 seconds, and give enough time for a fast reader to read from start to finish 3 times.

The best I could do is not show the path on the notification when you save an existing document, that is, not a new document or saving-as. By typing something like "Saved successfully" the notification would leave faster.

Note, in case you or anyone else reading this hasn't noticed: You can click anywhere in the notification to dismiss it.

**Comment by videosmith** [comment]
Not mission critical for me. No need to change it imo.

    On Wednesday, February 1, 2023, 03:43:08 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


I see... The path to the file is a long string of text. Kirigami is programmed in such way that the notification stays up for longer the longer the text is, so users have enough time to read everything. Other means of knowing "data saved successfully" aren't visible while in fullscreen, which is why I left the notification in place for this particular circumstance.

If I shorten or fix the notification's duration, it may not be enough time for slower readers to read. I don't know how Kirigami computes the time, but when I video edit, I usually follow this rule: "Any text that comes and goes should be relatively still for a period of at least 3 seconds, and give enough time for a fast reader to read from start to finish 3 times.

The best I could do is not show the path on the notification when you save an existing document, that is, not a new document or saving-as. By typing something like "Saved successfully" the notification would leave faster.

Note, in case you or anyone else reading this hasn't noticed: You can click anywhere in the notification to dismiss it.
