### ISSUE TITLE
options bar and screen save

### ISSUE THREAD

**Issue by vibperson** [Cuperino/QPrompt#160]
what i need to do to save this option? If i want to use bar - not pointers. It resets after close
![изображение](https://user-images.githubusercontent.com/126832236/222585902-6f1b167c-6fb9-4932-8467-e5c33467a12d.png)

and similar problem with displays. when i mark to use second - h mirrors, its also resets after close (on this pic i 've i screen but now i can't make screen 2nd)
![изображение](https://user-images.githubusercontent.com/126832236/222585869-a106b489-2038-4ffb-9458-d24a09358fa4.png)

**Comment by Cuperino** [comment]
Thanks for reporting. Always try to to separate each issue in a different report, as that helps with our tracking.

I'll dedicate this issue to the bar issue exclusively and make a new issue regarding the screens.

**Comment by Cuperino** [comment]
What operating system and QPrompt version are you using? You can find out QPrompt's version in the About Page. I ask because I wasn't able to replicate your issue with Bar not saving on my system.

**Comment by vibperson** [comment]
Qpromt v.1.1.5 (v.1.1/720a13) and Windows 10 x64 22H2

**Comment by Cuperino** [comment]
Excellent! Thanks.

**Comment by videosmith** [comment]
> what i need to do to save this option? If i want to use bar - not pointers. It resets after close ![изображение](https://user-images.githubusercontent.com/126832236/222585902-6f1b167c-6fb9-4932-8467-e5c33467a12d.png)
> 
> and similar problem with displays. when i mark to use second - h mirrors, its also resets after close (on this pic i 've i screen but now i can't make screen 2nd) ![изображение](https://user-images.githubusercontent.com/126832236/222585869-a106b489-2038-4ffb-9458-d24a09358fa4.png)

I have 1.1.5 on an x86_64 platform. the option selected persists correctly through a restart/reboot. Do you get pointers back when restarting? If not a possible culprit may be you're not seeing the bar since it's the same color as your background?

**Comment by videosmith** [comment]
Tried to Disable background transparency, upon application restart, setting ignored.

**Comment by Cuperino** [comment]
@vibperson, when you restarted the QPrompt and the `Indicator Bar` setting was ignored, were you restarting through a prompt to restart that QPrompt gave you, or did you restart by manually exiting the app and re-opening it?

**Comment by videosmith** [comment]
Even when uninstalling the .deb app and executing the AppImage file instead, the issue persists. 

Which files survive an 'apt purge qprompt' command?

**Comment by Cuperino** [comment]
Nothing should survive 'apt purge qprompt'.

**Comment by videosmith** [comment]
Tried another reboot, apt autoremove... no change.  Where are configuration files installed? Just in case something is stuck?

**Comment by Cuperino** [comment]
On Linux they install to `~/.config/Cuperino/qprompt.conf`.

Before deleting, please make a copy, and if QPrompt restarts correctly after deleting the original, upload the copy here for me to inspect.

A few betas also saved to `~/.config/Cuperino/QPrompt.conf`, but those settings are ignored and the file can be safely deleted.

**Comment by videosmith** [comment]
That fixed it. File was not updating. Removing it caused QPrompt to generate a new one.
![screen1](https://user-images.githubusercontent.com/88691671/222872722-02c1d703-c0a4-4f20-ae8f-bc1537988308.png)

[conf_archive.zip](https://github.com/Cuperino/QPrompt/files/10887341/conf_archive.zip)

**Comment by vibperson** [comment]
I've opened QPrompt put Bar and then i close it or press Quit in QPrompt.

**Comment by vibperson** [comment]
It dont ask me to restart if iu change pointers to bar. 
Reg manipulations didn't helped

**Comment by Cuperino** [comment]
Hello @vibperson,

I have good news.I managed to re-create the bug you were experiencing, and in the processed uncovered a different bug and fixed both.

Although I was able to fix the bug you are experiencing, I have to say that this bug is in part a bug in Windows 10 22H2 specifically. Windows 10 21H1, Windows 10 21H2 and Windows 11 22H2 are not subject to your issue and neither are KDE neon 22.04 Linux or MacOS 13.0.1 Ventura.

The issue was the following: When QPrompt starts for the first time, the problematic setting, which is called "styleState", should've been set to a default numeric value, but instead a text representation of the same value was being saved. This issue affected all systems and meant no setting was being loaded on when the app first launched, which made it default to a different setting. Fixing this bug did not solve the Windows 10 22H2 bug. 

On Windows 10 22H2, QPrompt to save the default value to the registry every time the program is run, even when there's already a value present. This meant Windows 10 22H2 was not reporting QPrompt with the correct value for "styleState" when the application started. This issue occurred because QPrompt did some additional processing to choose an arrow based on the system's language. Since users never got to experience the true initial value, because of the first bug, what I did was turn that unintentional default into the deliberate default choice, allowing me to eliminate the step that the bug that can only be experience in Windows 10 22H2.

The bug is fixed for both the v1.1 and v1.2 branches. It may take a few weeks before I make new builds. I'm out of time for this weekend, the next 3 weekends are committed, and these builds can take 2 or 3 days to make, due to issues that arise because of upstream changes, and the amount of testing involved.
