### ISSUE TITLE
Simplify multi-click text selection

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#164]
**Bug Description**
Double clicking on text to select it does not produce the expected results.

**Steps to Reproduce**
1. Double-click on "Thank" in Welcome script, word highlights as expected.
![1](https://user-images.githubusercontent.com/88691671/223608840-ad5c781f-56e1-4909-a5f7-0632c50e5785.png)

2. Click once on "Thank" immediately to deselect it, highlights sentence instead.
![2](https://user-images.githubusercontent.com/88691671/223608956-018459c7-172a-4275-9165-f071f5b19edb.png)

3. Click once on "Thank" immediately again deselects that sentence, highlights the next sentence.
![3](https://user-images.githubusercontent.com/88691671/223609100-6760ddb4-b50c-4e9e-aad6-7cf58b558e44.png)

4. Click once on "Thank" immediately again, pattern continues.
![4](https://user-images.githubusercontent.com/88691671/223609189-0db0d210-ba52-4d93-80ba-0b9fc23d64e2.png)

5. Another issue:  Clear all selection/reload Welcome script, double-click on "QPrompt". Word highlights as expected.
![5](https://user-images.githubusercontent.com/88691671/223609510-263ff98d-9be2-4184-97be-8ad851dbf426.png)

6. <(This action is intermittant.) Clicking once on "QPrompt" (or off of the word) does not deselect. Instead click-hold-drag on "QPrompt" results in individually selected letters depending on location and drag direction. Operator must manually drag to deselect all letters in "Qprompt".
![6](https://user-images.githubusercontent.com/88691671/223610121-059bddf9-ae72-4970-8dee-c3e4b067a523.png)

**Expected behavior**
Should select/deselect like behaviors in word processors

**Device information**
 - QPrompt Version: 1.1.5
 - Operating System: Debian Bullseye x64, latest updates

![7](https://user-images.githubusercontent.com/88691671/223610689-a580fa52-1877-4be9-a7d5-d198c51d39a0.png)

**Comment by Cuperino** [comment]
Some of this is intended behavior. Text selection is handled by Qt. I could theoretically change how it works, but I don't want to get into that. Maybe later, when I finally add fill support for images, which will require support for dragging.

> Click once on "Thank" immediately to deselect it, highlights sentence instead.

Clicking a third time after a double click, without moving the mouse is meant to select the current paragraph. This is the intended behavior, following the likes of LibreOffice, and Mozilla Firefox. The main difference is that the third click is usually tied to a short timer, but in QPrompt no such timer exists.

To deselect, move the cursor to point elsewhere and then click. The mouse must point at letters different from the previous click.

> Click once on "Thank" immediately again deselects that sentence, highlights the next sentence.

Automatic selection of the next paragraph is another feature of Qt, but unlike the previous one, this was not intended behavior. 

> Another issue: Clear all selection/reload Welcome script, double-click on "QPrompt". Word highlights as expected.

Clicks on Markers behave differently because markers are are html anchors in reality, and thus Qt treats them as such. Regarding its behavior, I can see why we wouldn't want it to be different.
