### ISSUE TITLE
Pressing Ctrl+U has no effect

### ISSUE THREAD

**Issue by HansVanNeck** [Cuperino/QPrompt#18]
You cannot underline text in Edit mode.  Nor  with the Underline Icon,
nor with Control U.

**Comment by Cuperino** [comment]
I have had this problem when the font in question does not support that particular font style (be it underline, italic or bold).

What font are you using?
What program was the text copied from?
What operating system were you running here?

**Comment by HansVanNeck** [comment]
It is not depended on the font. 
The text was inserted from Qprompt Windows 10.

I found hat if you first open de font color box, you the underline button works.  So it is a start up initialization problem

**Comment by Cuperino** [comment]
Very interesting! I'll try see if I can replicate it this way.

**Comment by Cuperino** [comment]
Confirmed as duplicate to bug in issue #25.

**Comment by Cuperino** [comment]
Bug is due to Qt's file dialog using Ctrl+U as a shortcut to move one directory above, and this shortcut not being disabled when the file dialog isn't shown.

All fixes are to be done upstream and not in QPrompt itself.

Some potential fixes are:

- Disable Ctrl+U shortcut in file dialog when the file dialog isn't being shown
- Remove Ctrl+U shortcut from file dialog

**Comment by Cuperino** [comment]
Issue fixed upstream.
