### ISSUE TITLE
Edited fonts not displaying properly

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#193]
**Bug Description**
Edited TTF fonts do not display correctly in Qprompt

**Steps to Reproduce**
1. In an attempt to create a workaround to display All Caps, I duplicated/edited the dejavu sans font family in FontForge by copying all uppercase glyphs into their corresponding lower case positions.
2. Opened Qprompt, Welcome text.
3. Selected the first paragraph and then selected modified font (see pic)
4. No apparent change with the modified font, other selected fonts display as expected.
5. Copy the selected text in Qprompt after attempting to change font, pasted in LibreOffice Writer, font displays as expected (see pic)
6. Edited fonts attached.

**Expected behavior**
Operation should perform the same in Qprompt as Writer.

**Screenshots** (optional)
![pic1](https://github.com/Cuperino/QPrompt/assets/88691671/ae232a72-4bf7-48dc-bced-222b1e44a1b4)
![screen](https://github.com/Cuperino/QPrompt/assets/88691671/50490d6c-78eb-42f3-983c-9b07234987a3)

**Device information**
 - QPrompt Version: 1.2 rev 5
 - Operating System: Debian 11 x86. LXQt

[fonts.zip](https://github.com/Cuperino/QPrompt/files/11783706/fonts.zip)

**Comment by Cuperino** [comment]
Hi @videosmith,

The reason that won't work with any of the following fonts:

- DejaVu Sans
- Kalpurush
- Libertinus
- OpenDislexyc
- Palanquin
- Scheherazade New
- Source Han Sans

is because these fonts are embedded into and loaded from QPrompt's binary executable, instead of loaded from the operating systems' fonts. This was done this way on purpose because embedding fonts into the binary is the only way one can provide access to a consistent set of fonts across all platforms, including platforms which provide no access to system fonts, such as: Android, iOS, and WASM.

While it should be possible to modify the CMakeLists.txt build scripts to use the embedded fonts for Android, iOS, WASM, and Haiku, but not on Windows, Mac, Linux, and FreeBSD, this is something I'd rather avoid because if I allow system fonts to be used for these fonts, I'd be opening the doors to the possibility of inconsistent prompting experiences from one operating system to the next, because of the differences present in variations of the fonts, or when a font that is expected cannot be found.

What I'm trying to say is that [it’s not a bug, it’s a feature](https://www.wired.com/story/its-not-a-bug-its-a-feature/).

**Comment by Cuperino** [comment]
Re-opening. I just realized the fonts are showing under a different name, meaning they should load despite the original still being impossible to override without recompilation. I need to look into why the caps did not display despite the variation having a different name.

**Comment by videosmith** [comment]
Could be some changes I neglected to make when editing copies of the font files.
At any rate, I've worked around the issue for myself by repeating the above process with Arial in my system fonts instead of your embedded ones.

Appears to display as expected.

![screen](https://github.com/Cuperino/QPrompt/assets/88691671/eec0ed57-e475-4be3-ae0b-45a8acfc4d59)
