### ISSUE TITLE
Editing in Prompt mode with mapped keys

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#229]
**Bug Description**
When double clicking in Prompt.mode to edit text,  typing with mapped keys like 'w' which invokes a scroll action here instead of typing text.

**Device information**
 - QPrompt Version: 1.2 r6
 - Operating System: Debian 12.1

**Comment by Cuperino** [comment]
This one's a bit tricky:

1. Users must be free to set any key as means to control the prompter with the keyboard
2. Users must be able to adjust the prompter speed from the "edit while prompting mode"
3. Users must be able to type while in "edit while prompting mode".

Now, these things are at odds with each other and, on top of this, I have no means to identify typeable keys to let those through. It wouldn't be fast enough nor would it cover all languages and type systems. If I allowed typeable keys to work, I'd be invalidating point number two.

One solution I can think of that wouldn't prevent the user from adjusting the prompter velocity is having the user specify a different set of keys to use to control the velocity in "edit while prompting mode". That would make the input configuration section more complex for users, and it might not be possible to achieve with global hotkeys, because in the work in progress implementation of global hotkeys it isn't possible to take the state of "edit while prompting mode" into consideration...

**Comment by Cuperino** [comment]
Marking as `wontfix` for now... It's more important to have global hotkeys and get that implementation right. QPrompt's current behavior closely matches what users would experience using global hotkeys, so it might be best to keep it this way.

I could add a warning indicating that if they set a typeable key to control the prompter, they won't be able to type those keys from "edit while prompting" mode. Then also add a link that shows more details on how to use the feature.
