### ISSUE TITLE
MD format looses formatting

### ISSUE THREAD

**Issue by HansVanNeck** [Cuperino/QPrompt#24]
[1.](url)  Save a file, now in html format in MD format
2. Close QPrompt
3. Open Qprompt.
4. Open de file
The content has now no visible formatting

Ad 1) This is the file (See also the attachment)
![image](https://user-images.githubusercontent.com/95466879/145371115-4f5d3ba4-8685-47b6-bdf3-32888a871748.png)
and save it as t.md
ad 4) Open the file t.md

Annoying is that suddenly the font size adjuster is set to 144%. 
![image](https://user-images.githubusercontent.com/95466879/145371612-1f6ed028-3a7d-4ff8-a28d-15eecd37569b.png)

![image](https://user-images.githubusercontent.com/95466879/145371823-17fe9c15-9f64-49f6-9083-fe35d373040d.png)
Manually adjust the font size to 100%
![image](https://user-images.githubusercontent.com/95466879/145372030-b9b527f6-f19e-4744-8403-d378a7011ed8.png)

And you see also that now the ETA is 11 seconds. 

[t.md](https://github.com/Cuperino/QPrompt/files/7683921/t.md)
[G0240NL_VeldK.zip](https://github.com/Cuperino/QPrompt/files/7683931/G0240NL_VeldK.zip)

**Comment by Cuperino** [comment]
Because saving as markdown would require a separate editor interface to avoid making matters confusing, and because it would require implementing a parser for HTML to Markdown conversion and this conversion would result in data loss due of he nature of the Markdown format, I've decided to make Markdown files read only. Attempting to save a Markdown file will result in a Save dialog being prompted to save under a different format, treating the open file as a new document.
