### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#36]
Will the hotkeys/shortcuts be the same as those in Imaginary?

**Comment by Cuperino** [comment]
They're mostly the same, and they're customizable.

The only differences are:
- To start prompting you press **F9** instead of F8. (If you re-assign this key to a key with a type-able character, you'll have to press Ctrl+[key] to start the prompter.)
- To move through markers, instead of the Home/End keys you use **Ctrl+PageUp/Ctrl+PageDown**. (If you re-assign these keys, the Ctrl modifier will apply to whichever key you've re-assigned to.)

To customize inputs go to:
1. Main menu (top left)
2. Control settings
3. Keyboard Inputs
An overlay will load giving you the ability to modify inputs. If you set an input as a key that has already been set, the new key won't be registered. You must first re-assign the key holding that value and then assign the new key to that key's old value.
