### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by nobicycle** [Cuperino/QPrompt#38]
### Scroll down for build instructions

**Bug Description**
Cannot find file:  QPrompt-1.0.0/3rdparty/kirigami/kirigami.pro.

```
$ make
cd 3rdparty/kirigami/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /mnt/Archives/archives/Office/Presentation/qprompt/QPrompt-1.0.0/3rdparty/kirigami/kirigami.pro ) && make -f Makefile 
Cannot find file: /mnt/Archives/archives/Office/Presentation/qprompt/QPrompt-1.0.0/3rdparty/kirigami/kirigami.pro.
make: *** [Makefile:50: sub-3rdparty-kirigami-make_first] Error 2
```

**Steps to Reproduce**
Download latest release.
cd QPrompt-1.0.0
qmake QPrompt.pro
make

**Detailed description of display configuration** (if applicable)

Installed: 
kcoreaddons 5.89.0-1 (1.3 MiB 3.4 MiB) [kf5] (Installed)
kirigami2 5.89.0-1 (563.9 KiB 1.9 MiB) [kf5] (Installed)
ki18n 5.89.0-1 (1.9 MiB 17.6 MiB) [kf5] (Installed)
clang-13.0.0-4  
clazy-1.10-2  
compiler-rt-13.0.0-2  
qt6-5compat-6.2.2-1  
qt6-declarative-6.2.2-1  
qt6-positioning-6.2.2-1  
qt6-quick3d-6.2.2-1  
qt6-quicktimeline-6.2.2-1
qt6-serialport-6.2.2-1  
qt6-shadertools-6.2.2-1  
qt6-tools-6.2.2-1  
qt6-webchannel-6.2.2-1  
qt6-webengine-6.2.2-2  
yaml-cpp-0.7.0-2  
qtcreator-6.0.1-1

**Device information**
$ uname -a
Linux tower 5.10.89-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:09:17 UTC 2021 x86_64 GNU/Linux
 - QPrompt Version: QPrompt-1.0.0

**Comment by kbimplis** [comment]
What would the dependencies and build process be for building on Mac OSX? Thanks

**Comment by Cuperino** [comment]
Hi @kbimplis, On macOS, Windows, and for the Linux AppImage, the project uses [KDE's Craft meta build system](https://community.kde.org/Craft). I haven't been able to create a single working build that does not using Craft. So, if you don't want to use Craft, it's on you to figure out how. I personally like Craft because it is very effective in streamlining the distribution process to other platforms. I'm going to rely on third party build instructions to save time in maintaining these instructions.

### Setup Craft (build Windows, macOS, and Linux AppImage)
Follow the respective instruction to setup Craft for your operating system. Linux, Windows, and macOS are confirmed to work. The Android is created manually using different instructions.
https://community.kde.org/Craft#Setting_up_Craft

- macOS https://community.kde.org/Guidelines_and_HOWTOs/Build_from_source/Mac#Installation_using_Craft
- Window https://community.kde.org/Guidelines_and_HOWTOs/Build_from_source/Windows
- Linux AppImage https://community.kde.org/Craft/Linux

### Setup QPrompt inside of Craft's build environment

1. Start Craft environment (you should be given the OS specific command to start Craft at the end of Craft's setup)
2. Install [QPrompt's Craft repository](https://github.com/Cuperino/craft-blueprints-qprompt)
```
craft --add-blueprint-repository https://github.com/Cuperino/craft-blueprints-qprompt.git
```
3. (optional) Set KDE Frameworks to a version that is stable and works well with all supported OS. (Determining which version works right with all OS is a process done experimentally.) For QPrompt v1.0, I used version`5.86.0` of KDE Frameworks. The version used will appear inside of QPrompt's About page.
```
craft --set version=[version] cuperino/qprompt
```
4. (optional) Set which version of QPrompt you wish to install. (optional) At the time of writing it is only possible to install from GirHub's the main branch, which is the default. The version used will appear inside of QPrompt's About page.
```
craft --set version=[version] cuperino/qprompt
```
5. Run QPrompt's build command
```
craft qprompt
```
6. (optional) To download the latest source code run:
```
craft --update qprompt
```
7. (optional) To package QPrompt for your system run:
```
craft --package qprompt
```
The resulting package will be saved in Craft's `tmp` folder.

For additional Craft commands and other Craft supported platforms, please refer to [Craft's documentation](https://community.kde.org/Craft).

### Additional information

- **It is recommended that you have at least 6 GB of RAM to compile QPrompt.**
- When building QPrompt on **Windows** you may find the build process fails near the end. This is due to a [bug possibly with the build system](https://bugs.kde.org/show_bug.cgi?id=445248) where symbolic links of two different icon packages conflict with each other. At the time of writing, you'll need to modify the CMake.install script generated by Craft, and remove the lines pointing to conflicting icons by hand, then run the following command to complete the CMake installation process prior to packaging:
```
craft --install qprompt
```

**Comment by kbimplis** [comment]
Thank you. Much appreciated

**Comment by videosmith** [comment]
After running the apt command to satisfy all dev-dependencies: The following various messages appeared after running 'cmake -B build/ .'

-- Check for working CXX compiler: /usr/bin/c++ - skipped
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CMake Warning at CMakeLists.txt:240 (find_package):
  By not providing "FindKF5Crash.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5Crash",
  but CMake did not find one.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Could not find a package configuration file provided by "KF5Crash" with any
  of the following names:

    KF5CrashConfig.cmake
    kf5crash-config.cmake
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CMake Warning at CMakeLists.txt:245 (find_package):
  By not providing "FindQHotkey.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QHotkey", but
  CMake did not find one.

  Could not find a package configuration file provided by "QHotkey"
  (requested version 1.5.0) with any of the following names:

    QHotkeyConfig.cmake
    qhotkey-config.cmake

  Add the installation prefix of "QHotkey" to CMAKE_PREFIX_PATH or set
  "QHotkey_DIR" to a directory containing one of the above files.  If
  "QHotkey" provides a separate development package or SDK, be sure it has
  been installed.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- The following OPTIONAL packages have not been found:

 * KF5Crash, Graceful handling of application crashes.
 * QHotkey (required version >= 1.5.0)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CMake Warning at CMakeLists.txt:240 (find_package):
  By not providing "FindKF5Crash.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5Crash",
  but CMake did not find one.

  Could not find a package configuration file provided by "KF5Crash" with any
  of the following names:

    KF5CrashConfig.cmake
    kf5crash-config.cmake

  Add the installation prefix of "KF5Crash" to CMAKE_PREFIX_PATH or set
  "KF5Crash_DIR" to a directory containing one of the above files.  If
  "KF5Crash" provides a separate development package or SDK, be sure it has
  been installed.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Did I miss a step?

**Comment by Cuperino** [comment]
You did not miss any required steps.

QHotkeys library only enables a single shortcut (Meta+Alt+F10) to toggle making all windows fully semi-transparent, and not just their backgrounds, on or off. Future versions of QPrompt will make more and better use of QHotkeys, and I will update these instructions accordingly then. The reason v1.1 makes use of said library for an optional feature almost no one needs is because I needed to make sure that I could successfully distribute the 3rd party library in all of QPrompt's distribution formats prior to making the commitment to add hotkey support to more parts of the program.

KF5Crash was incorporated to help me find the cause behind a few crashes, all of which have been addressed. The only benefit installing this library now is QPrompt will automatically try to restart if it crashes. There are no other benefits like file recovery, yet. I haven't gotten v1.1 to crash on Linux or Mac. Only the Windows and Haiku versions can be crashed in my experience and, in the case of Windows, this crash is difficult to trigger involuntarily in my opinion.

**Comment by videosmith** [comment]
A few more items (lines between rows of asterisks) - apologies for the long entry but wasn't certain if just terminal window snippets would be sufficient:

root@xxx-Laptop:/home/xxxxxx/Desktop/QPrompt-1.1.2# mkdir build
root@xxx-Laptop:/home/xxxxxx/Desktop/QPrompt-1.1.2# cmake -B build/ .
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done


******************************************************************************************************************************************
-- Check for working CXX compiler: /usr/bin/c++ - skipped
******************************************************************************************************************************************


-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found KF5Kirigami2: /usr/lib/x86_64-linux-gnu/cmake/KF5Kirigami2/KF5Kirigami2Config.cmake (found version "5.78.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.78.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.78.0") 
-- Found KF5IconThemes: /usr/lib/x86_64-linux-gnu/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.78.0") 
-- Found KF5: success (found suitable version "5.78.0", minimum required is "5.68.0") found components: Kirigami2 I18n CoreAddons IconThemes 
CMake Warning at CMakeLists.txt:240 (find_package):
  By not providing "FindKF5Crash.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5Crash",
  but CMake did not find one.

  Could not find a package configuration file provided by "KF5Crash" with any
  of the following names:

    KF5CrashConfig.cmake
    kf5crash-config.cmake

  Add the installation prefix of "KF5Crash" to CMAKE_PREFIX_PATH or set
  "KF5Crash_DIR" to a directory containing one of the above files.  If
  "KF5Crash" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at CMakeLists.txt:245 (find_package):
  By not providing "FindQHotkey.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QHotkey", but
  CMake did not find one.

  Could not find a package configuration file provided by "QHotkey"
  (requested version 1.5.0) with any of the following names:

    QHotkeyConfig.cmake
    qhotkey-config.cmake

  Add the installation prefix of "QHotkey" to CMAKE_PREFIX_PATH or set
  "QHotkey_DIR" to a directory containing one of the above files.  If
  "QHotkey" provides a separate development package or SDK, be sure it has
  been installed.


-- Installing in the same prefix as Qt, adopting their path scheme.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.68.0)
 * QT
 * Qt5Qml (required version >= 5.15.2)
 * Qt5QmlModels (required version >= 5.15.2)
 * Qt5Quick
 * Qt5Svg
 * Qt5Gui
 * Qt5QuickControls2
 * Qt5Network
 * Qt5X11Extras
 * Qt5
 * KF5Kirigami2 (required version >= 5.68.0)
 * Gettext
 * KF5I18n (required version >= 5.68.0)
 * KF5CoreAddons (required version >= 5.68.0)
 * Qt5Widgets (required version >= 5.14.0)
 * KF5IconThemes (required version >= 5.68.0)
 * KF5 (required version >= 5.68.0)
 * Qt5Core

-- The following OPTIONAL packages have not been found:

 * KF5Crash, Graceful handling of application crashes.
 * QHotkey (required version >= 1.5.0)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxxxx/Desktop/QPrompt-1.1.2/build


root@xxx-Laptop:/home/xxxxxx/Desktop/QPrompt-1.1.2# cmake --build build/
Scanning dependencies of target pofiles-ab72fa3e2a4b170ad4e3282d4adeb4c4
[  7%] Generating mo...
[  7%] Built target pofiles-ab72fa3e2a4b170ad4e3282d4adeb4c4
Scanning dependencies of target tsfiles-ab72fa3e2a4b170ad4e3282d4adeb4c4
[ 14%] Generating ts...
[ 14%] Built target tsfiles-ab72fa3e2a4b170ad4e3282d4adeb4c4
Scanning dependencies of target qprompt_autogen
[ 21%] Automatic MOC and UIC for target qprompt
[ 21%] Built target qprompt_autogen
[ 28%] Automatic RCC for icons/icons.qrc
[ 35%] Automatic RCC for qml.qrc
[ 42%] Automatic RCC for assets.qrc
Scanning dependencies of target qprompt
[ 50%] Building CXX object build/CMakeFiles/qprompt.dir/qprompt_autogen/mocs_compilation.cpp.o                                                                          
In file included from /home/xxxxxx/Desktop/QPrompt-1.1.2/build/build/qprompt_autogen/YJWVCCTYAF/../../../../src/prompter/documenthandler.h:83,
                 from /home/xxxxxx/Desktop/QPrompt-1.1.2/build/build/qprompt_autogen/YJWVCCTYAF/moc_documenthandler.cpp:10,
                 from /home/xxxxxx/Desktop/QPrompt-1.1.2/build/build/qprompt_autogen/mocs_compilation.cpp:2:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In constructor ‘Marker::Marker(const QString&, int, int, int, const QString&, const QString&, int)’:


******************************************************************************************************************************************
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:67: warning: unused parameter ‘length’ [-Wunused-parameter]
   36 |       Marker(const QString& text, const int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                       ~~~~~~~~~~^~~~~~

/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:105: warning: unused parameter ‘keyLetter’ [-Wunused-parameter]
   36 | t int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                  ~~~~~~~~~~~~~~~^~~~~~~~~
******************************************************************************************************************************************



[ 57%] Building CXX object build/CMakeFiles/qprompt.dir/main.cpp.o
In file included from /home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/documenthandler.h:83,
                 from /home/xxxxxx/Desktop/QPrompt-1.1.2/src/main.cpp:62:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In constructor ‘Marker::Marker(const QString&, int, int, int, const QString&, const QString&, int)’:


******************************************************************************************************************************************
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:67: warning: unused parameter ‘length’ [-Wunused-parameter]
   36 |       Marker(const QString& text, const int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                       ~~~~~~~~~~^~~~~~
******************************************************************************************************************************************


/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:105: warning: unused parameter ‘keyLetter’ [-Wunused-parameter]
   36 | t int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                  ~~~~~~~~~~~~~~~^~~~~~~~~

[ 64%] Building CXX object build/CMakeFiles/qprompt.dir/prompter/documenthandler.cpp.o                                                                                  
In file included from /home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/documenthandler.h:83,
                 from /home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/documenthandler.cpp:72:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In constructor ‘Marker::Marker(const QString&, int, int, int, const QString&, const QString&, int)’:


******************************************************************************************************************************************
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:67: warning: unused parameter ‘length’ [-Wunused-parameter]
   36 |       Marker(const QString& text, const int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                       ~~~~~~~~~~^~~~~~

/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:105: warning: unused parameter ‘keyLetter’ [-Wunused-parameter]
   36 | t int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                  ~~~~~~~~~~~~~~~^~~~~~~~~

/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/documenthandler.cpp: In member function ‘void DocumentHandler::preventSleep(bool)’:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/documenthandler.cpp:954:41: warning: unused parameter ‘prevent’ [-Wunused-parameter]
  954 | void DocumentHandler::preventSleep(bool prevent) {
      |                                    ~~~~~^~~~~~~
******************************************************************************************************************************************


[ 71%] Building CXX object build/CMakeFiles/qprompt.dir/prompter/markersmodel.cpp.o
In file included from /home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.cpp:22:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In constructor ‘Marker::Marker(const QString&, int, int, int, const QString&, const QString&, int)’:


******************************************************************************************************************************************
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:67: warning: unused parameter ‘length’ [-Wunused-parameter]
   36 |       Marker(const QString& text, const int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                       ~~~~~~~~~~^~~~~~

/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:36:105: warning: unused parameter ‘keyLetter’ [-Wunused-parameter]
   36 | t int position, const int length, const int key, const QString& keyLetter, const QString& url, const int requestType)
      |                                                  ~~~~~~~~~~~~~~~^~~~~~~~~

/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In member function ‘Marker MarkersModel::binarySearch(int, int, int, bool)’:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:27:8: warning: ‘virtualMarker.Marker::key’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   27 | struct Marker {
      |        ^~~~~~
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:27:8: warning: ‘virtualMarker.Marker::requestType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h: In member function ‘Marker MarkersModel::nextMarker(int)’:
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:27:8: warning: ‘invalidPositionMarker.Marker::key’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   27 | struct Marker {
      |        ^~~~~~
/home/xxxxxx/Desktop/QPrompt-1.1.2/src/prompter/markersmodel.h:27:8: warning: ‘invalidPositionMarker.Marker::requestType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
******************************************************************************************************************************************


[ 78%] Building CXX object build/CMakeFiles/qprompt.dir/qprompt_autogen/EWIEGA46WW/qrc_qml.cpp.o                                                                        
[ 85%] Building CXX object build/CMakeFiles/qprompt.dir/qprompt_autogen/EWIEGA46WW/qrc_assets.cpp.o 


******************************************************************************************************************************************                                                                    
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [build/CMakeFiles/qprompt.dir/build.make:271: build/CMakeFiles/qprompt.dir/qprompt_autogen/EWIEGA46WW/qrc_assets.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:368: build/CMakeFiles/qprompt.dir/all] Error 2
gmake: *** [Makefile:182: all] Error 2
******************************************************************************************************************************************


root@xxx-Laptop:/home/xxxxxx/Desktop/QPrompt-1.1.2#

**Comment by Cuperino** [comment]
The following error:
```
c++: fatal error: Killed signal terminated program cc1plus
```
means the operating system prevented compilation from completing. In the context of QPrompt, this usually  happens because the computer being used to compile QPrompt lacks or cannot allocate the necessary RAM to complete the compilation process.

A minimum of 6 GB of RAM is recommended to compile QPrompt. Two workarounds can be used to compile QPrompt in 64 bit architecture systems with only 4 GBs of RAM: 

## First workaround: Reduce the number of cores used by the compiler to reduce RAM usage
You can reduce the number of "jobs" or CPU cores dedicated to building QPrompt by passing the `--parallel 1` argument to cmake's build instruction.
```
cmake --build build/ --parallel 1
```
This solution is not guaranteed to work because QPrompt's RAM requirements increase as features grow, and I haven't tried compiling with 4 GB of RAM in a while. Nevertheless, if the approach does work, no modifications to QPrompt would be needed.

## Second workaround: Prevent included Asian languages font from being bundled with QPrompt
1. Remove the following line from `src/assets.qrc`
``` 
        <file alias="fonts/sourcehansans.ttc">fonts/editor/SourceHanSans/SourceHanSans-Regular.ttc</file>
```
2. And remove the following lines from `src/kirigami_ui/EditorToolbar.qml`
```
            FontLoader {
                id: asianSeriousSansFont
                source: "fonts/sourcehansans.ttc"
            }
```
```
                MenuItem {
                    text: i18nc("FontName (Translatable font details)", "Source Han Sans (CH, JP, KO)")
                    onTriggered: viewport.prompter.document.fontFamily = asianSeriousSansFont.name
                }
```

## Additional note

It is not possible to build QPrompt on 32 bit systems because those systems allocate considerably less than 4 GB of RAM to the compiler. Cross-compilation is a requirement to make a fully featured build for a 32 bit operating system.

## Regarding formatting
You can use the triple quotes described on this guide to format terminal output on GitHub: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by videosmith** [comment]
Understood and thank you. The only computer I have with sufficient memory is an old mac pro. Can a compile be performed from a linux Live cd?

**Comment by Cuperino** [comment]
> The only computer I have with sufficient memory is an old mac pro. Can a compile be performed from a linux Live cd?

Running from a live system may increase RAM requirements. If the Mac's CPU is of Intel architecture, and the Mac can boot a distribution modern enough to meet QPrompt's dependencies, then yes, you should be able to compile and package QPrompt from a Linux live CD or live USB flash.

Just keep in mind that Mac boot loaders work different to regular PCs and extra considerations may be needed to get a Linux system to boot.

**Comment by videosmith** [comment]
Thank you I will look into it. Hopefully booting with refind will work.
