### ISSUE TITLE
Improve animation performance

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#46]
Would reducing the color depth to 8-bit/256 colors improve scolling performance?

Raspberry Pi 4b Debian Bullseye 64bit latest updates

**Comment by Cuperino** [comment]
I don't know.

Theoretically, it should improve because there's less work on the operating system's compositor, but inside QPrompt graphics may still be rendered at 8-bit color depth... I know this is true for the countdown, but I don't know whether this would hold true for the rest of the scene graph.

I'm going to close this issue because improving performance for projections is covered at issue #42 and, if you omit the countdown and projection features, QPrompt's animation is significantly more fluid and faster to process than Imaginary Teleprompter's on GPU accelerated hardware and multi threaded environments.
