### ISSUE TITLE
Improve consistency for marker / anchor tag's visual representation

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#47]
Your default script has several marked elements with no visible tags, however when I add a marker to highlighted text, over and under-scores decorate the text.

**Detailed description of display configuration** (if applicable)

...

**Screenshots** (if applicable)

...
![Screenshot from 2022-01-30 11-00-38](https://user-images.githubusercontent.com/88691671/151708759-1f70db7b-e042-4205-86e9-8e4a92ca85dc.png)
![Screenshot from 2022-01-30 11-01-37](https://user-images.githubusercontent.com/88691671/151708769-46cb48ce-5176-4114-bc45-bee9f5a0a307.png)

**Device information**
 - Operating System: [Raspberry Pi 4b Debian Bullseye 64bit latest updates]
 - QPrompt Version: [e.g. 1.0.0]

...

**Comment by Cuperino** [comment]
Since documents in the editor are HTML, marker were made using HTML anchor tags to improve compatibility with scripts coming from Imaginary Teleprompter. Nevertheless, markers created inside of QPrompt are not represented in the same way as traditional anchors. This makes it seem like the markers from the default script aren't showing, when in fact they just look like ordinary hyperlinks, and this here was the mistake.

Both regular anchors and markers created from within QPrompt should use the same visual representation for consistency purposes.

**Comment by Cuperino** [comment]
Issue fixed for next release.

Anchors in HTML from other sources now look like anchors created in QPrompt.
