### ISSUE TITLE
Frame scroll controls become invisible when background is set to black

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#48]
**Bug Description**
When selecting Black as the background color, the right-side scroll bar is invisible.

**Expected behavior**

Invert the scroll elements colors?

**Device information**
 - Operating System: [e.g. Linux, Windows, macOS, iOS, or Android]
 - QPrompt Version: [e.g. 1.0.0]

**Comment by Cuperino** [comment]
This is an unintended consequence of the scrollbar being composed of opaque black rectangles. Inverting colors is computationally inexpensive but may result in a distracting amount of contrast with the background because humans are more susceptible to differences between light colors than we are to differences between dark colors. 

I'll see if I can use an accent color for the scrollbar.

**Comment by Cuperino** [comment]
Used color theory and played with opacity to ensure the scroll indicator is always visible in the most common backgrounds, which are black, white and the default gray. This change also increases performance while prompting, but I doubt that it is perceptible.

Fix will be out in the next update.
