### ISSUE TITLE
Pointers customization

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#51]
Are the pointers based on ascii characters and if so, can they be user-defined (character, size, color etc.) like any other text in the app?

**Comment by Cuperino** [comment]
They're done with vector shapes instead of ASCII. It could be done with ASCII, the only reason to avoid characters is that it's harder to center vertically because of the different character sizes, but this could be solved with a fixed font.

If you were to set other characters or shapes, what would these be?

**Comment by videosmith** [comment]
A very low priority, however something like this ▶ that changes from white when scrolling text to red when paused?

With the same drag ability to vertically position it like the other pointers when specifying a custom region.

**Comment by Cuperino** [comment]
I love the idea of having the pointer change colors to indicate playback state. This gives the reader information without them having to break eye contact.

I'll try my best to add character pointers that are centered at all times, so no additional adjustments are necessary.

**Comment by videosmith** [comment]
I think the ability to drag the pointer to any position vertically is an asset. I have several clients that request custom pointer positions.

**Comment by Cuperino** [comment]
Done.
