### ISSUE TITLE
Disappearing menus

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#52]
Thinking that the underscored **G** in the Load Menu text was a keyboard shortcut, pressing Alt-G resulted in menus disappearing. Restarting the app restored them.

![Screenshot from 2022-02-02 12-53-21](https://user-images.githubusercontent.com/88691671/152210640-7518d4fc-219f-4bf9-83e2-8b10c24454c7.png)

![Screenshot from 2022-02-02 12-54-41](https://user-images.githubusercontent.com/88691671/152210660-09d31933-07ea-4fcb-8732-c6ec24270a11.png)

**Device information**
 - Operating System: [Debian64 Bullseye, latest updates]
 - QPrompt Version: [e.g. 1.0.0]
 - RPi 4B

**Comment by Cuperino** [comment]
Pressing `Alt-G` from the main menu results in the guide being loaded for Linux (AppImage, Snap, and Flatpak both arm64 and amd64) and Windows distributions, and pressing `Option-G` or `Command-G` results in no action for macOS.

This bug is probably specific to the version of Kirigami provided by your distribution, since the only difference between all the aforementioned versions and the Deb package is I don't control the versions of library dependencies in use.

What versions of KDE Frameworks and Qt do you see listed on the "Libraries in use" section of the `About QPrompt` page?

**Comment by videosmith** [comment]
![Screenshot from 2022-02-02 18-40-18](https://user-images.githubusercontent.com/88691671/152256236-f294ba62-5031-4671-a749-c51c01df9542.png)

**Comment by Cuperino** [comment]
Thanks! I was able to replicate the issue on a arm64 Debian 11 (Bullseye) install running KDE Plasma, that comes with the same library versions: KDE Frameworks 5.78.0 and Qt 5.15.2.

The bug is indeed specific to said version of KDE Frameworks, which is provided by the OS. The issue does not occur on the same system if you run from Flatpak, which comes with KDE Frameworks 5.88.0.

Unfortunately there's nothing we can do here besides run from Flatpak, as updating to use the libraries from the Debian testing repository could bring make the system buggy and unstable.
