### ISSUE TITLE
Keyboard shortcuts not persisting

### ISSUE THREAD

**Issue by hafner** [Cuperino/QPrompt#53]
**Bug Description**

If you set a custom keyboard shortcut the next time you open the application it is reverted back to default

**Device information**
 - Operating System: Windows 10
 - QPrompt Version:1.0.0

**Comment by Cuperino** [comment]
Haven't gotten around to making shortcuts persistent... I'll make this a priority.

**Comment by Cuperino** [comment]
Out of curiosity @hafner: What values are you customizing your keyboard inputs to and why?

**Comment by hafner** [comment]
I have a wireless usb pointer that acts as a keyboard wedge(normally used for PowerPoint) and it doesn't allow you to change the keys. So I have start/stop mapped to enter instead of space. Switch mode mapped to F1 instead of F9 as my laptop has shrunken F keys and F9 is hard to find in a hurry.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cuperino** [comment]
I see... Thanks for the feedback!

**Comment by DrJPK** [comment]
Hi @Cuperino I would also greatly appreciate this enhancement.  I am using a stream deck as a controller so am mapping the shortcuts to F13-F24 range so that it doesn't clash with anything else I'm using in Windows.

If you know where in the source code they are actually defined/initialised, I might be able to find some time to work out some way of writing them out to / reading them in from a text .conf file that might work across platforms. I'm thinking something in a ~/.qprompt/ directory???

**Comment by Cuperino** [comment]
Hello @DrJPK,

My apologies I haven't been able to work on this yet. It's been a busy month and the hardware I used to develop QPrompt broke, but I've worked around it. (You can find more details about this in the project's Telegram chat.)

Adding persistence should be quite easy. The challenging part is having the program show the correct values on the key mapping UI when a new session starts; some tweaks or rewriting of the UI might be required.

### Key mapping code

Key mapping is split across 3 files:

- [_src/prompter/Prompter.qml_](https://github.com/Cuperino/QPrompt/blob/main/src/prompter/Prompter.qml#L161) [161-171] Holds the values for default input keys.
- [_src/kirigami_ui/InputsOverlay.qml_](https://github.com/Cuperino/QPrompt/blob/main/src/kirigami_ui/InputsOverlay.qml) [entire file] Is the UI to configure input keys.
- [_src/kirigami_ui/KeyInputButton.qml_](https://github.com/Cuperino/QPrompt/blob/main/src/kirigami_ui/KeyInputButton.qml) [entire file] Is an abstraction of the button component used to assign keys.

### How data is saved to disk

Configurations are saved to disk using the [Qt.labs.settings module](https://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html). This module is an API to access the [QSettings](https://doc.qt.io/qt-5/qsettings.html) from QML without the need to add additional C++ backend. Since The Qt Company does not guarantee the Qt.labs module will remain compatible in future versions of the software, if support for it is dropped the QSettings Class should be used instead, ideally through the creation of a shim layer.

The advantage in using either Settings or QSettings is this layer provides a cross-platform abstraction to save simple configurations to disk. You can see where data is stored for each platform over at https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes

### Prior knowledge

This is not an exhaustive list. Understanding how the following things work will ease the development process:

- [Connections QML](https://doc.qt.io/qt-5/qml-qtqml-connections.html)
- [Settings QML](https://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html)
- [QSettings](https://doc.qt.io/qt-5/qsettings.html)

### Good practice

Please note that a [declarative programming approach](https://www.youtube.com/watch?v=krMxE_ar55g) should always preferred over imperative programming when developing QPrompt.

### Things that may need to occur for key mappings to be preserved

1. The `keys` JavaScript object at _Prompter.qml_ ([lines 162-171](https://github.com/Cuperino/QPrompt/blob/main/src/prompter/Prompter.qml#L162)) may need to be replaced with an instance of Settings QML type. Use of the Settings type would allow for a more declarative style of programming to be used for this feature.
2. See how the current default button labels are hard coded at [lines 53-60](https://github.com/Cuperino/QPrompt/blob/main/src/kirigami_ui/InputsOverlay.qml#L53) of _InputsOverlay.qml_? The button's `getKeyText` method could be triggered from the `Component.onCompleted` slot to dynamically choose which text will be shown on the InputsOverlay UI upon loading.
3. The `onSetKey` slot of each `KeyInputButton` component (currently located at [lines: 64, 69, 74, 79, 84, 89](https://github.com/Cuperino/QPrompt/blob/main/src/kirigami_ui/InputsOverlay.qml#L64) of _InputsOverlay.qml_) could trigger saving the respective button setting to disk. The use of this imperative style of programming may not be necessary were the keys object replaced with a Settings object.

**Comment by Cuperino** [comment]
@DrJPK, just checking, have you been able to get acquainted with the code?

**Comment by Cuperino** [comment]
Quick update, I've finished implementing persistent shortcuts. The fix will be available in the next release.
