### ISSUE TITLE
qprompt not saving anything 

### ISSUE THREAD

**Issue by ashrafkawasmi** [Cuperino/QPrompt#75]
**Bug Description**

change region
change keyboard shortcuts
change anything

on restart of the software - back to default

it does not save it in program settings - nor in the savs as file
...

**Steps to Reproduce**

1. ...
2. ...

**Expected behavior**

...

**Detailed description of display configuration** (if applicable)

...

**Screenshots** (if applicable)

...

**Device information**
 - Operating System: [e.g. Linux, Windows, macOS, iOS, or Android]
 - QPrompt Version: [e.g. 1.0.0-beta-003]

**Additional context**

...

**Comment by Cuperino** [comment]
Hello @ashrafkawasmi,

Thank you for making this report.

The current version, 1.0, saves most values properly. The only values documented not to persist in the current version are:
- Keyboard shortcuts
- Screen configuration

Keyboard shortcuts were reported on issue #53. Please make sure the issue hasn't already been reported before making a new report to avoid duplication.

For this report to be valid, you must clearly indicate what is broken. "Anything" not saving is not factually correct, unless you're using old versions of QPrompt, in which case you must update. The beta you've indicated 1.0.0-beta-003 is not supported anymore. Please update to the latest version, 1.0.0.

You must also indicate which operating system you've found the bug in. Otherwise us developers may not be able to replicate the issue.

**Comment by Cuperino** [comment]
@ashrafkawasmi I'm unable to replicate having changes in reading region not save. To be able to replicate, I need more details such as your Operating System and the version of QPrompt, and the Qt framework used by your version of QPrompt. These last two are found at QPrompt's About page.

I'm closing the issue because there's not enough information to replicate reading region settings not saving, and the rest of the report was either already reported or is not specific enough. Feel free to re-open if you can provide the requested details.
