### ISSUE TITLE
Cannot save files on Android platform

### ISSUE THREAD

**Issue by Miguel-Rodrigues** [Cuperino/QPrompt#81]
**Bug Description**
Cannot save files on android platform.

**Steps to Reproduce**
1. Start a new file
2. Fill teleprompter with some text
3. Hamburger menu > Save As > ep01.txt
4. Throws a message box saying the file does not exists and creates an empty file with the specified name.

**Expected behavior**
To save the file into the selected folder.

**Detailed description of display configuration** (if applicable)

**Screenshots** (optional)
![Screenshot_2022-04-02-13-16-44-963_com cuperino qprompt](https://user-images.githubusercontent.com/10254384/161382810-af2b608d-355a-4889-9f60-6f72b1d02ad7.jpg)
![Screenshot_2022-04-02-13-17-54-343_com google android documentsui](https://user-images.githubusercontent.com/10254384/161382901-86fe6bf7-ead0-441e-a7d0-1f040c127f5c.jpg)

**Device information**
 - QPrompt Version: 1.0.0
 - Operating System: Android 11 (MIUI 12.5.7)

**Additional context**

**Comment by Cuperino** [comment]
Issue confirmed. Thanks for reporting.

**Comment by Cuperino** [comment]
Hello @Miguel-Rodrigues, I noticed you translated QPrompt to Portuguese on the fork that you made. If you make a pull request and sign the CLA that comes with the PR, I can incorporate your translation into the next minor release v1.1.1, which I plan on releasing later this month. For that release I also hope to solve this bug here with file saving in Android, and polish the Android interface a little more.

Please note that I will still not be calling v1.1.x version production ready on Android, because I consider one should be able to remotely control QPrompt, and it should better integrate with the operating system before it's ready for production use.

**Comment by Cuperino** [comment]
It may take longer than I had anticipated to fix this issue...

Here are some links for personal reference:

- https://www.volkerkrause.eu/2019/02/16/qt-open-files-on-android.html
- https://forum.qt.io/topic/113328/how-to-convert-android-content-url-and-use-it-to-open-file
- https://github.com/mahdize/CrossQFile/issues/1
- https://forum.qt.io/topic/113335/qfiledialog-getopenfilename-always-returns-empty-string-on-android/2
- https://developer.android.com/training/permissions/evaluating#open-documents
- https://developer.android.com/training/data-storage/shared/documents-files
- https://stackoverflow.com/questions/11987193/android-androidtargetsdkversion-and-androidmaxsdkversion
- https://doc.qt.io/qt-5/qsavefile.html

**Comment by Cuperino** [comment]
Reverted goal back to v1.1.1 now that two libraries that could serve this purpose have become viable options.

**Comment by Cuperino** [comment]
Issue fixed for v1.1.1, to be released later today.

Nevertheless, for now you can only load files created from QPrompt due to limitations in Qt's API that must be overcome either by using one of the aforementioned libraries or by upgrading to Qt 6, which is currently not an option due to KDE dependencies not being compatible yet.
