### ISSUE TITLE
Mice and touchpad not processing wheel event properly on macOS

### ISSUE THREAD

**Issue by jjbutler83** [Cuperino/QPrompt#83]
Original title: Mouse scroll wheel not working on MacBook Pro M1 Max / MacOS with external mouse

The scroll wheel is not controlling the scroll or scroll speed on my M1 Max MacBook Pro running Mac OS Monterey. On the previous program, Imaginary Prompter, this worked 100% perfectly.

**Comment by Cuperino** [comment]
The default behavior in QPrompt is not the same as Imaginary Teleprompter's. In Imaginary Teleprompter, the scroll wheel changes velocity, on QPrompt it scrolls like any regular app would. To make QPrompt behave like Imaginary Teleprompter you can do one of two things:

1. Go to `Menu > Control Settings` and check "Use scroll as velocity dial". This will make QPrompt do a scroll like Imaginary Teleprompter's.
2. Press `Command` while using the scroll wheel. This will toggle scroll behaviors, enabling you to switch between traditional scrolling and dial like scrolling.

MacOS currently prevents "Dial like scrolling" from working at all with the touchpad. Nevertheless, this limitation doesn't apply to the external mice I've tested with.

**Comment by jjbutler83** [comment]
Thanks for getting back to me, option one, as you laid out, didn't make a difference when toggled before, when I get a chance, I will try method two to see if that yields a positive result.

Thanks again,

Justin Butler
Freelance Event Technician (Video)
J. Butler Production Services, LLC
(V1/GFX/Playback/Virtual/vMix)
C: (407) 448-7476
E: ***@***.******@***.***>
W: http://jb-ps.com

**Comment by Cuperino** [comment]
Try method one as well, but with a different external mouse; preferably one that's not a Magic Mouse.

**Comment by jjbutler83** [comment]
Hello again,

So, after some testing, here is where I am at:

I have tried both a Bluetooth wireless Logitech M590 as well as a wired Logitech G502 Hero mouse.

In Imaginary Teleprompter, both work flawlessly and the velocity control with the scroll wheel is accurate and responds almost as good as Telescript with a traditional rotary controller. Both mice work and they function the same.

However, as far as qPrompt goes, we seem to be going backwards, which is a little suprising as this product has been positioned to be a newer replacement for the former.

Anyway, with qPrompt, the Logitech M509 bluetooth wireless mouse, no matter what settings or key presses, it NEVER controls the velocity function. Have tried all known methods and what you even mentioned previously.

The wired Logitech G502 Hero mouse WILL take velocity control, but it is very slow/delayed and really unresponsive, especially when compared with Imaginary Teleprompter.

So, for me anyway, will have to stick with Imaginary Teleprompter as it does exactly what I need it to do.

Hopefully you can work the issues out of qPrompt as I can see the potential for it to eventually take it’s predecessor’s spot.

Thanks again,

-J

From: Javier O. Cordero Pérez ***@***.***>
Date: Wednesday, April 6, 2022 at 8:11 PM
To: Cuperino/QPrompt ***@***.***>
Cc: jjbutler83 ***@***.***>, Author ***@***.***>
Subject: Re: [Cuperino/QPrompt] Mouse scroll wheel behavior different to Imaginary Teleprompter's (Issue #83)

Try method one as well, but with a different external mouse; preferably one that's not a Magic Mouse.

**Comment by Cuperino** [comment]
Thank you for sharing your detailed feedback @jjbutler83, I truly appreciate it.

My apologies for the inconvenience. I will look more deeply too find what's causing mice not to work properly on macOS.

With regards to why the wheel feels delayed and unresponsive, this happens because there's a throttle functionality in QPrompt that is meant for better control with touchpads, which a features that couldn't be accomplished with Imaginary Teleprompter due to its underlying architecture. Unfortunately, this feature cannot be disabled in the current version of QPrompt, but you will be able to turn it on or off and adjust the throttle for the next release, QPrompt 1.1.

At least I am glad to see Imaginary Teleprompter is doing exactly what you need it to. Situations like this one are why it continues to be supported and will continue to be maintained indefinitively. I do not expect QPrompt to satisfy all of Imaginary Teleprompter's potential use cases, but I do expect it to eventually become the better option for your present needs.

I will notify you here when I think these issues are fixed, and when the beta and final 1.1 releases become available.

Once again, thank you for your contribution.

**Comment by Cuperino** [comment]
@jjbutler83, what version of macOS are you currently running?

**Comment by Cuperino** [comment]
Issues fixed for next release: v1.1.

**Comment by Cuperino** [comment]
New beta and release candidate is out. This issue should be fixed.
https://github.com/Cuperino/QPrompt/releases/tag/v1.1.0-rc-1
