### ISSUE TITLE
Incorrect background transparency

### ISSUE THREAD

**Issue by waylonwang** [Cuperino/QPrompt#88]
**Bug Description**
When the transparency of the background is 100, the interface is displayed normally. When the transparency is lower than 100, the transparency of the entire line area where the button that starts the prompting is located directly becomes 0.

**Steps to Reproduce**
1.Change the background transparency directly

**Expected behavior**
The background transparency of the row where the start prompt button is located is displayed according to the set transparency

**Screenshots** 
![2](https://user-images.githubusercontent.com/7424276/169679976-7953674a-64ac-4085-83f8-e6464d77b186.png)
![1](https://user-images.githubusercontent.com/7424276/169679983-1851b47d-a6fa-4207-979e-9ea3d48182f8.png)

**Device information**
 - QPrompt Version: [QPrompt 1.1.0-beta-3 (05/21/2022)](https://github.com/Cuperino/QPrompt/releases/tag/v1.1.0-beta-3)
 - Operating System: Windows 11

**Comment by Cuperino** [comment]
Hi @waylonwang,

Thanks for reporting.

There's a bug in the 1.1.0 betas which is causing the mobile interface's "teleprompter state toggle button" to be shown in some of the desktop versions of QPrompt. When the button is shown, vertical prompting and editing space is reduced. Then the prompter's viewport and background do not extend to the bottom because the button bellow them is not supposed to be there. This is inconvenient when combined with transparency because, in order to achieve the slightest transparency, the window's background must be fully invisible. Since no semi transparent background is covering it, this results in the fully transparent gap that you see.

The issue seems to be caused by a bug in the Kirigami that keeps coming and going. Kirigami is one of the libraries used to create QPrompt and is foundational to its user interface. What I do to avoid this bug is test and include only versions of Kirigami that don't come with this bug on any platform. Since this process is long and tedious, I only do it for final releases and skip it for the beta builds.

I'm also not sure what in Kirigami is triggering this issue. When I run QPrompt [QPrompt 1.1.0-beta-3 (05/21/2022)](https://github.com/Cuperino/QPrompt/releases/tag/v1.1.0-beta-3) on Windows 10, the issue only happens the first time that I launch QPrompt for a Windows session. If I close QPrompt and launch it again, the issue doesn't happen. But on other platforms I get completely different behavior.

What I've done is change the design so backgrounds are always present to fill the gap when it appears.

**Comment by Cuperino** [comment]
Here's a new beta with the fix. Enjoy!
https://github.com/Cuperino/QPrompt/releases/tag/v1.1.0-beta-4
